a : Number
b : Number
c : Number
 : [Number <> Number <> Number]
a <> b : Number <> Number <> Number
a <> b <> c : (Number <> Number <> Number) , (Number <> Number <> Number)
[a <> b <> c] : [Number <> Number <> Number] <> [Number <> Number <> Number]
[a <> b <> c] : [Number <> Number <> Number] , [Number <> Number <> Number]
[a , b , c] : [1 , 2 , 3] => [1 , 2 , 3]
[a , b , c] : [Number , Number , Number] , [Number , Number , Number]