a : Number
b : Number
c : Number
<expression> : Tuple(Tuple(Number, Number), Number)
<expression> : Tuple(Tuple(Number, Number), Number)
<expression> : Tuple(Tuple(Tuple(Number, Number), Number), Tuple(Tuple(Number, Number), Number))
<expression> : Tuple(Tuple(Tuple(Number, Number), Number), Tuple(Tuple(Number, Number), Number))
<expression> : Tuple(Tuple(Tuple(Number, Number), Number), Tuple(Tuple(Number, Number), Number))
<expression> : Tuple(Tuple(Tuple(Number, Number), Number), Tuple(Tuple(Number, Number), Number))
<expression> : Tuple(Tuple(Tuple(Number, Number), Number), Tuple(Tuple(Number, Number), Number))
