(module
  (import "env" "print" (func $print (param f64)))
  (memory i64 20)
  (export "memory" (memory 0))
  (global $arena_ptr (mut i64) (i64.const 1000000))
  (type $func_sig (func (param i64) (param f64) (result f64)))
  (func $__builtin_id (param $ctx i64) (param $x f64) (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local.get $x)
  )
  (func $main (export "main") (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local $arr f64)
    (local $a f64)
    (local $b f64)
    (local $c f64)
    (local $d f64)
    (local $arr_y f64)
    (local $e f64)
    (local.set $arr (block (result f64) (local.set $__tmp_ptr (global.get $arena_ptr)) (global.set $arena_ptr (i64.add (global.get $arena_ptr) (i64.const 40))) (f64.store offset=0 (local.get $__tmp_ptr) (f64.const 5)) (f64.store offset=8 (local.get $__tmp_ptr) (f64.const 3)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const 10)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const 20)) (f64.store offset=32 (local.get $__tmp_ptr) (f64.const 30)) (f64.convert_i64_u (local.get $__tmp_ptr))))
    (local.set $a (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $arr))))
                (if (result f64) (f64.lt (f64.const 0) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=16 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ))
    (local.set $b (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $arr))))
                (if (result f64) (f64.lt (f64.const 1) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=24 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ))
    (local.set $c (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $arr))))
                (if (result f64) (f64.lt (f64.const 2) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=32 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ))
    (local.set $d (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $arr))))
                (if (result f64) (f64.lt (f64.const 3) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=40 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ))
    (local.set $arr_y (block (result f64) (local.set $__tmp_ptr (global.get $arena_ptr)) (global.set $arena_ptr (i64.add (global.get $arena_ptr) (i64.const 40))) (f64.store offset=0 (local.get $__tmp_ptr) (f64.const 5)) (f64.store offset=8 (local.get $__tmp_ptr) (f64.const 3)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const 100)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const 200)) (f64.store offset=32 (local.get $__tmp_ptr) (f64.const 300)) (f64.convert_i64_u (local.get $__tmp_ptr))))
    (local.set $e (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $arr_y))))
                (if (result f64) (f64.lt (f64.const 1) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=24 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ))
    (call $print (f64.add (f64.add (f64.add (local.get $a) (local.get $b)) (local.get $c)) (local.get $e)))
    (f64.const 0)
  )
  (table 2 funcref)
  (elem (i32.const 0) $__builtin_id)
)