(module
  (import "env" "print" (func $print (param f64)))
  (memory i64 20)
  (export "memory" (memory 0))
  (global $arena_ptr (mut i64) (i64.const 1000000))
  (type $func_sig (func (param i64) (param f64) (result f64)))
  (func $__builtin_id (param $ctx i64) (param $x f64) (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local.get $x)
  )
  (func $main (export "main") (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local $obj f64)
    (local.set $obj (block (result f64) (local.set $__tmp_ptr (global.get $arena_ptr)) (global.set $arena_ptr (i64.add (global.get $arena_ptr) (i64.const 32))) (f64.store offset=0 (local.get $__tmp_ptr) (f64.const 4)) (f64.store offset=8 (local.get $__tmp_ptr) (f64.const 2)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const nan)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const nan)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const 10)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const 20)) (f64.convert_i64_u (local.get $__tmp_ptr))))
    (call $print (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $obj))))
                (if (result f64) (f64.lt (f64.const 1) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=24 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ))
    (f64.const 0)
  )
  (table 2 funcref)
  (elem (i32.const 0) $__builtin_id)
)