(module
  (import "env" "print" (func $print (param f64)))
  (memory i64 20)
  (export "memory" (memory 0))
  (global $arena_ptr (mut i64) (i64.const 1000000))
  (type $func_sig (func (param i64) (param f64) (result f64)))
  (func $__builtin_id (param $ctx i64) (param $x f64) (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local.get $x)
  )
  (func $__func_2 (param $ctx i64) (param $x f64) (result f64)
    (local $__free_a f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local.set $__free_a (f64.load (i64.add (i64.const 24) (local.get $ctx))))
    (if (f64.gt (local.get $x) (f64.const 1000000))
      (then
        (local.set $__tmp_ptr (i64.trunc_f64_u (local.get $x)))
        (if (f64.eq (f64.load offset=0 (local.get $__tmp_ptr)) (f64.const 4))
          (then
            (if (f64.lt (f64.const 0) (f64.load offset=8 (local.get $__tmp_ptr)))
              (then
                (local.set $__tmp_f64 (f64.load offset=16 (local.get $__tmp_ptr)))
                (if (f64.eq (local.get $__tmp_f64) (local.get $__tmp_f64))
                  (then (local.set $x (local.get $__tmp_f64)))
                )
              )
            )
          )
        )
      )
    )
    (f64.add (local.get $x) (local.get $__free_a))
  )
  (func $maker (param $ctx i64) (param $a f64) (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (if (f64.gt (local.get $a) (f64.const 1000000))
      (then
        (local.set $__tmp_ptr (i64.trunc_f64_u (local.get $a)))
        (if (f64.eq (f64.load offset=0 (local.get $__tmp_ptr)) (f64.const 4))
          (then
            (if (f64.lt (f64.const 1) (f64.load offset=8 (local.get $__tmp_ptr)))
              (then
                (local.set $__tmp_f64 (f64.load offset=24 (local.get $__tmp_ptr)))
                (if (f64.eq (local.get $__tmp_f64) (local.get $__tmp_f64))
                  (then (local.set $a (local.get $__tmp_f64)))
                )
              )
            )
          )
        )
      )
    )
    (block (result f64) (local.set $__tmp_ptr (global.get $arena_ptr)) (global.set $arena_ptr (i64.add (global.get $arena_ptr) (i64.const 32))) (i32.store (local.get $__tmp_ptr) (i32.const 2)) (f64.store offset=8 (local.get $__tmp_ptr) (f64.const 2)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const 1)) (f64.store offset=24 (local.get $__tmp_ptr) (local.get $a)) (f64.convert_i64_u (local.get $__tmp_ptr)))
  )
  (func $main (export "main") (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local $maker f64)
    (local $f f64)
    (local $b f64)
    (local.set $maker (f64.const 500001))
    (local.set $f (block (result f64)
                (local.set $__tmp_f64 (local.get $maker))
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $__tmp_f64))))
                (call_indirect (type $func_sig)
                    ;; CTX
                    (select 
                        (i64.const 0)
                        (local.get $__tmp_ptr)
                        (f64.lt (local.get $__tmp_f64) (f64.const 1000000))
                    )
                    ;; ARG
                    (f64.const 10)
                    ;; FUNC_INDEX
                    (select
                        (i32.trunc_f64_u (f64.sub (f64.max (local.get $__tmp_f64) (f64.const 500000)) (f64.const 500000)))
                        (i32.trunc_f64_u (f64.load offset=8 (local.get $__tmp_ptr)))
                        (f64.lt (local.get $__tmp_f64) (f64.const 1000000))
                    )
                )
            ))
    (local.set $b (block (result f64)
                (local.set $__tmp_ptr_expand (i64.trunc_f64_u (f64.abs (call $__list_alloc_2 (local.get $f) (f64.const 5)))))
                (local.set $__tmp_f64 (f64.load offset=16 (local.get $__tmp_ptr_expand))) ;; funcPtr (e0)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $__tmp_f64))))
                (call_indirect (type $func_sig)
                    ;; CTX
                    (select 
                        (i64.const 0)
                        (local.get $__tmp_ptr)
                        (f64.lt (local.get $__tmp_f64) (f64.const 1000000))
                    )
                    ;; ARG (e1)
                    (f64.load offset=24 (local.get $__tmp_ptr_expand))
                    ;; FUNC_INDEX
                    (select
                        (i32.trunc_f64_u (f64.sub (f64.max (local.get $__tmp_f64) (f64.const 500000)) (f64.const 500000)))
                        (i32.trunc_f64_u (f64.load offset=8 (local.get $__tmp_ptr)))
                        (f64.lt (local.get $__tmp_f64) (f64.const 1000000))
                    )
                )
            ))
    (call $print (local.get $b))
    (f64.const 0)
  )
  (table 4 funcref)
  (elem (i32.const 0) $__builtin_id)
  (elem (i32.const 2) $__func_2)
  (elem (i32.const 1) $maker)
  (func $__list_alloc_2 (param $elem0 f64) (param $elem1 f64) (result f64)
    (local $ptr i64)
    (local.set $ptr (global.get $arena_ptr))
    (i32.store (local.get $ptr) (i32.const 3)) ;; Tag=3 (List)
    (f64.store offset=8 (local.get $ptr) (f64.const 2)) ;; Length=2
    (f64.store offset=16 (local.get $ptr) (local.get $elem0))
    (f64.store offset=24 (local.get $ptr) (local.get $elem1))
    (global.set $arena_ptr (i64.add (global.get $arena_ptr) (i64.const 32)))
    (f64.convert_i64_u (local.get $ptr))
  )
)