(module
  (import "env" "print" (func $print (param f64)))
  (memory i64 20)
  (export "memory" (memory 0))
  (global $arena_ptr (mut i64) (i64.const 1000000))
  (type $func_sig (func (param i64) (param f64) (result f64)))
  (func $__builtin_id (param $ctx i64) (param $x f64) (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local.get $x)
  )
  (func $f (param $ctx i64) (param $x f64) (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (if (f64.gt (local.get $x) (f64.const 1000000))
      (then
        (local.set $__tmp_ptr (i64.trunc_f64_u (local.get $x)))
        (if (f64.eq (f64.load offset=0 (local.get $__tmp_ptr)) (f64.const 4))
          (then
            (if (f64.lt (f64.const 0) (f64.load offset=8 (local.get $__tmp_ptr)))
              (then
                (local.set $__tmp_f64 (f64.load offset=16 (local.get $__tmp_ptr)))
                (if (f64.eq (local.get $__tmp_f64) (local.get $__tmp_f64))
                  (then (local.set $x (local.get $__tmp_f64)))
                )
              )
            )
          )
        )
      )
    )
    (f64.add (local.get $x) (f64.const 1))
  )
  (func $g (param $ctx i64) (param $obj f64) (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (if (f64.gt (local.get $obj) (f64.const 1000000))
      (then
        (local.set $__tmp_ptr (i64.trunc_f64_u (local.get $obj)))
        (if (f64.eq (f64.load offset=0 (local.get $__tmp_ptr)) (f64.const 4))
          (then
            (if (f64.lt (f64.const 2) (f64.load offset=8 (local.get $__tmp_ptr)))
              (then
                (local.set $__tmp_f64 (f64.load offset=32 (local.get $__tmp_ptr)))
                (if (f64.eq (local.get $__tmp_f64) (local.get $__tmp_f64))
                  (then (local.set $obj (local.get $__tmp_f64)))
                )
              )
            )
          )
        )
      )
    )
    (f64.add (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $obj))))
                (if (result f64) (f64.lt (f64.const 0) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=16 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ) (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $obj))))
                (if (result f64) (f64.lt (f64.const 1) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=24 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ))
  )
  (func $main (export "main") (result f64)
    (local $__tmp_ptr i64)
    (local $__tmp_ptr_expand i64)
    (local $__tmp_f64 f64)
    (local $obj f64)
    (local $a f64)
    (local $f f64)
    (local $b f64)
    (local $g f64)
    (local $c f64)
    (local.set $obj (block (result f64) (local.set $__tmp_ptr (global.get $arena_ptr)) (global.set $arena_ptr (i64.add (global.get $arena_ptr) (i64.const 32))) (f64.store offset=0 (local.get $__tmp_ptr) (f64.const 4)) (f64.store offset=8 (local.get $__tmp_ptr) (f64.const 2)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const nan)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const nan)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const 10)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const 20)) (f64.convert_i64_u (local.get $__tmp_ptr))))
    (local.set $a (block (result f64)
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $obj))))
                (if (result f64) (f64.lt (f64.const 1) (f64.load offset=8 (local.get $__tmp_ptr)))
                    (then (f64.load offset=24 (local.get $__tmp_ptr)))
                    (else (f64.const nan))
                )
            ))
    (local.set $f (f64.const 500001))
    (local.set $b (block (result f64)
                (local.set $__tmp_f64 (local.get $f))
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $__tmp_f64))))
                (call_indirect (type $func_sig)
                    ;; CTX
                    (select 
                        (i64.const 0)
                        (local.get $__tmp_ptr)
                        (f64.lt (local.get $__tmp_f64) (f64.const 1000000))
                    )
                    ;; ARG
                    (block (result f64) (local.set $__tmp_ptr (global.get $arena_ptr)) (global.set $arena_ptr (i64.add (global.get $arena_ptr) (i64.const 32))) (f64.store offset=0 (local.get $__tmp_ptr) (f64.const 4)) (f64.store offset=8 (local.get $__tmp_ptr) (f64.const 2)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const nan)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const nan)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const 100)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const 200)) (f64.convert_i64_u (local.get $__tmp_ptr)))
                    ;; FUNC_INDEX
                    (select
                        (i32.trunc_f64_u (f64.sub (f64.max (local.get $__tmp_f64) (f64.const 500000)) (f64.const 500000)))
                        (i32.trunc_f64_u (f64.load offset=8 (local.get $__tmp_ptr)))
                        (f64.lt (local.get $__tmp_f64) (f64.const 1000000))
                    )
                )
            ))
    (local.set $g (f64.const 500002))
    (local.set $c (block (result f64)
                (local.set $__tmp_f64 (local.get $g))
                (local.set $__tmp_ptr (i64.trunc_f64_u (f64.abs (local.get $__tmp_f64))))
                (call_indirect (type $func_sig)
                    ;; CTX
                    (select 
                        (i64.const 0)
                        (local.get $__tmp_ptr)
                        (f64.lt (local.get $__tmp_f64) (f64.const 1000000))
                    )
                    ;; ARG
                    (block (result f64) (local.set $__tmp_ptr (global.get $arena_ptr)) (global.set $arena_ptr (i64.add (global.get $arena_ptr) (i64.const 32))) (f64.store offset=0 (local.get $__tmp_ptr) (f64.const 4)) (f64.store offset=8 (local.get $__tmp_ptr) (f64.const 2)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const nan)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const nan)) (f64.store offset=16 (local.get $__tmp_ptr) (f64.const 5)) (f64.store offset=24 (local.get $__tmp_ptr) (f64.const 5)) (f64.convert_i64_u (local.get $__tmp_ptr)))
                    ;; FUNC_INDEX
                    (select
                        (i32.trunc_f64_u (f64.sub (f64.max (local.get $__tmp_f64) (f64.const 500000)) (f64.const 500000)))
                        (i32.trunc_f64_u (f64.load offset=8 (local.get $__tmp_ptr)))
                        (f64.lt (local.get $__tmp_f64) (f64.const 1000000))
                    )
                )
            ))
    (call $print (local.get $a))
    (call $print (local.get $b))
    (call $print (local.get $c))
    (f64.const 0)
  )
  (table 4 funcref)
  (elem (i32.const 0) $__builtin_id)
  (elem (i32.const 1) $f)
  (elem (i32.const 2) $g)
)