[package]
name = "sign"
version = "0.1.67"
edition = "2021"
license = "https://github.com/johnny-shaman/sign/License"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
