func_with_defaults : (Tuple(String, String) -> Number)
result1 : Number
result2 : Tuple(Tuple((Tuple(String, String) -> Number), Number), String)
result3 : Tuple((String -> Number), Number)
result4 : Tuple(Tuple((Tuple(String, String) -> Number), Number), Number)
result5 : Tuple(Tuple((Tuple(String, String) -> Number), Number), Number) | Unit
result6 : Tuple(Tuple((Tuple(String, String) -> Number), Number), Number) | Unit
