_ = [ ]*
__ = [ ]+

Expression
  = Define
  / Apply
  / Lambda
  / Product
  / number

Define  = name _ ":" _ Expression               // 本当は型推論をロジックに含んでおく

Apply   = (Lambda / name) __ Expression         // nameがfunctionである場合は推論可能

Lambda  = name (__ name)* _ "?" _ Expression

Product = Value _ (__ / ",") _ Expression

Value   = name / number

name    = [a-zA-Z_] [0-9a-zA-Z_]*
number  = "-"? [0-9]+
